### ISSUE TITLE
Redundant comma and space when paraphrasing

### ISSUE THREAD

**Issue by Davideko212** [HTL3R-Typst/htl3r-da#94]
![Image](https://github.com/user-attachments/assets/ffdefd00-bbcd-454a-8b60-bf54958d2eb9)

From the source:
`Neben Profinet, EtherCat und co. hat sich dieses Protokoll für die industrielle Kommunikation über Ethernet-Leitungen etabliert. @ethernet-bus-protocols-comp[comp]`

From `refs.yml`:
```
ethernet-bus-protocols-comp:
  type: article
  title: "EtherNet/IP, EtherCAT, Profinet and Modbus TCP: which protocol is right for you?"
  author: Jeremy Pollard
  url:
    value: https://www.controldesign.com/connections/data-acquisition-monitoring/article/55249378/ethernet-ip-ethercat-profinet-and-modbus-tcp-which-protocol-is-right-for-you
    date: 2025-02-17
  date: 2024-12-12
```
